### ISSUE TITLE
Provide access to keyvals via the FIXClient instance to facilitate mnemonic manufacture of outbound messages

### ISSUE THREAD

**Issue by salmdax** [hpn777/fixio#12]
When manufacturing a message destined for `client.send`, it would be useful to have access to `keyvals` from the utils directly from the FIXClient instance, so that in lieu of tag numbers, one can specify the tags using the mnemonic tag name equivalents.

For example, instead of: 

```
const sendLogon = function () {
    client.send({
	'35': 'A',
...
```

one could do: 

```
const sendLogon = function () {
    const msg = {};
    msg[keyvals.MsgType] = 'A';
...
    client.send(msg);
...
```

**Comment by hpn777** [comment]
It is accessible as you've described. Please take a look at https://github.com/hpn777/fixio/blob/ad8b518fa7f392ffd66e0ed9d5aa6c4b66fb68e3/src/fix.ts#L6

You can load keyvals directly from the module.

**Comment by salmdax** [comment]
Thank you for the quick response!
